apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config-map
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: 0.0.0.0:5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: registry
  labels:
    name: registry
spec:
  replicas: 1
  selector:
    name: registry
  template:
    metadata:
      labels:
        name: registry
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: registry:2.4.1
        name: registry
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          hostPort: 5001
        # I am not sure this even does anything
        env:
        - name: DOCKER_OPTS
          value: "--insecure-registry=0.0.0.0:5000"
        volumeMounts:
        - mountPath: /opt/docker
          name: registry-config
      - image: hyper/docker-registry-web
        name: frontend
        imagePullPolicy: Always
        env:
        - name: REGISTRY_URL
          value: "http://localhost:5000/v2"
        - name: REGISTRY_NAME
          value: "localhost:5000"
        ports:
        - containerPort: 8080
          hostPort: 8083
      volumes:
      - name: registry-config
        configMap:
          name: registry-config-map
          items:
          - key: config.yml
            path: registry/
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    name: registry
  ports:
  - name: registry
    port: 5001
    targetPort: 5001
  - name: frontend
    port: 8083
    targetPort: 8083
