apiVersion: v1
kind: ReplicationController
metadata:
  name: gogs
  labels:
    name: gogs
spec:
  replicas: 1
  selector:
    name: gogs
  template:
    metadata:
      labels:
        name: gogs
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gogs/gogs
        name: gogs
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          hostPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: gogs
spec:
  selector:
    name: gogs
  ports:
  - port: 3001
    targetPort: 3001
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: gogs
#   annotations:
#     traefik.frontend.rule.type: pathprefixstrip
# spec:
#   rules:
#   - host: gogs.minikube
#     http:
#       paths:
#       - backend:
#           serviceName: gogs
#           servicePort: 3001
