---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gogs-persistent-data
  labels:
    type: local
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/gogs_persistent_data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gogs-persistent-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gogs
  labels:
    name: gogs
spec:
  replicas: 1
  selector:
    name: gogs
  template:
    metadata:
      labels:
        name: gogs
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gogs/gogs
        name: gogs
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          hostPort: 3001
        volumeMounts:
        - mountPath: /data
          name: gogs-persistent-data
      volumes:
      - name: gogs-persistent-data
        persistentVolumeClaim:
          claimName: gogs-persistent-claim
---
apiVersion: v1
kind: Service
metadata:
  name: gogs
spec:
  selector:
    name: gogs
  ports:
  - port: 3001
    targetPort: 3001
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: gogs
#   annotations:
#     traefik.frontend.rule.type: pathprefixstrip
# spec:
#   rules:
#   - host: gogs.minikube
#     http:
#       paths:
#       - backend:
#           serviceName: gogs
#           servicePort: 3001
